In [35]:
import pandas as pd

In [36]:
df=pd.read_csv("C:\\Users\\4HIN\\Downloads\\imdb.csv")
df

,fn,tid,title,wordsInTitle,url,imdbRating,ratingCount,duration,year,type,...,Short,Sport,TalkShow,Thriller,War,Western,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,titles01/tt0012349,tt0012349,Der Vagabund und das Kind (1921),der vagabund und das kind,http://www.imdb.com/title/tt0012349/,8.4,40550,3240,1921,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,titles01/tt0015864,tt0015864,Goldrausch (1925),goldrausch,http://www.imdb.com/title/tt0015864/,8.3,45319,5700,1925,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
2,titles01/tt0017136,tt0017136,Metropolis (1927),metropolis,http://www.imdb.com/title/tt0017136/,8.4,81007,9180,1927,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
3,titles01/tt0017925,tt0017925,Der General (1926),der general,http://www.imdb.com/title/tt0017925/,8.3,37521,6420,1926,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4,titles01/tt0021749,tt0021749,Lichter der Gro√üstadt (1931),lichter der gro stadt,http://www.imdb.com/title/tt0021749/,8.7,70057,5220,1931,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14756,titles04/index.html.9989,tt0672488,Peep Show Sectioning (TV Episode 2005),peep show sectioning tv episode,http://www.imdb.com/title/tt0672488/,7.7,135,1440,2005,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14757,titles04/index.html.9992,tt0675644,Playhouse 90 The Miracle Worker (TV Episode 1957),playhouse the miracle worker tv episode,http://www.imdb.com/title/tt0675644/,7.3,8,5400,1957,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14758,titles04/index.html.9994,tt0679222,Private Screenings Robert Mitchum and Jane Rus...,private screenings robert mitchum and jane rus...,http://www.imdb.com/title/tt0679222/,7,20,3600,1996,video.episode,...,0,0,1,0,0,0,NaN,NaN,NaN,NaN
14759,titles04/index.html.9995,tt0680064,Providence All the King's Men (TV Episode 2002),providence all the king s men tv episode,http://www.imdb.com/title/tt0680064/,NaN,NaN,3600,2002,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14760,titles04/index.html.9997,tt0681024,QI Adam (TV Episode 2003),qi adam tv episode,http://www.imdb.com/title/tt0681024/,7.6,89,1800,2003,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

In [ ]:
Q7

In [38]:
result = df.loc[4, 'imdbRating']
result

'8.7'

In [ ]:
Q8

In [40]:
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')
shortest_movie = df.loc[df['duration'].idxmin(), 'title']
longest_movie = df.loc[df['duration'].idxmax(), 'title']

print(f"Shortest movie: {shortest_movie}")
print(f"Longest movie: {longest_movie}")

Shortest movie: Traffic Crossing Leeds Bridge (1888)
Longest movie: Scarface - Toni\

In [ ]:
Q9

In [41]:
df['year'] = pd.to_datetime(df['year'], errors='coerce')
df['imdbRating'] = pd.to_numeric(df['imdbRating'], errors='coerce')
sorted_df = df.sort_values(by=['year', 'imdbRating'], ascending=[True, False])
sorted_df.reset_index(drop=True, inplace=True)

print(sorted_df)

                             fn        tid  \
0      titles03/index.html.3586  tt0322023
1      titles02/index.html.1970  tt1137936
2      titles03/index.html.1193  tt0063950
3      titles03/index.html.4523  tt0520589
4      titles03/index.html.4554  tt0566900
...                         ...        ...
14756  titles04/index.html.9737  tt0499516
14757  titles04/index.html.9748  tt0502664
14758  titles04/index.html.9751  tt0504240
14759   titles04/index.html.976  tt0040928
14760   titles04/index.html.984  tt0041085

                                                   title  \
0                                                   Die\
1      Weeds - Kleine Deals unter Nachbarn If You Wor...
2                                            Scooby Doo\
3                                        Becker He Said\
4                       Duck Dodgers Of Course You Know\
...                                                  ...
14756                                              Look\
14757                     Hinterm Mond gleich links Eat\
14758                   Das A-Team When You Comin' Back\
14759                                           Ustedes\
14760               Abbott and Costello Meet the Killer\

                                            wordsInTitle  \
0                                                Mommie\
1       Then Why Do You Kill Yourself Working? (TV Ep...
2                   Where Are You! (TV Series 1969‚Äì1972)
3                             She Said (TV Episode 1999)
4       This Means War and Peace: Part 2 (TV Episode ...
...                                                  ...
14756   Up in the Sky! The Amazing Story of Superman ...
14757                                             Drink\
14758             Range Rider?: Part 2 (TV Episode 1983)
14759                                   los ricos (1948)
14760                               Boris Karloff (1949)

                                                     url  imdbRating  \
0                                            Die! (2003)         NaN
1      weeds kleine deals unter nachbarn if you work ...         NaN
2                     scooby doo where are you tv series         NaN
3                     becker he said she said tv episode         NaN
4      duck dodgers of course you know this means war...         NaN
...                                                  ...         ...
14756  look up in the sky the amazing story of superm...         NaN
14757                                              Dick\         NaN
14758  das a team when you comin back range rider par...         NaN
14759                                  ustedes los ricos         NaN
14760  abbott and costello meet the killer boris karloff         NaN

                                             ratingCount  duration       year  \
0                   http://www.imdb.com/title/tt0322023/       6.4 1682-01-01
1                                                    8.4     314.0 1800-01-01
2                                                    7.9   13948.0 1800-01-01
3                                                    7.2      22.0 1800-01-01
4                                                    8.1      19.0 1800-01-01
...                                                  ...       ...        ...
14756                                                  8     841.0        NaT
14757  hinterm mond gleich links eat drink dick mary ...       NaN        NaT
14758                                                7.7      98.0        NaT
14759                                                7.7     251.0        NaT
14760                                                7.1    2476.0        NaT

       type  ... Short Sport TalkShow Thriller  War  Western  Unnamed: 44  \
0      5400  ...     0     0        0        0    0        0          0.0
1      2008  ...     0     0        0        0    0        0          0.0
2      1972  ...     0     0        0        0    0        0          0.0
3      1999  ...     0     0        0        0    0        0          0.0
4      2005  ...     0     0        0        0    0        0          0.0
...     ...  ...   ...   ...      ...      ...  ...      ...          ...
14756  2006  ...     0     0        0        0    0        0          0.0
14757    90  ...     0     0        1        0    0        0          0.0
14758  1983  ...     0     0        0        0    0        0          0.0
14759  1948  ...     0     0        0        0    0        0          0.0
14760  1949  ...     0     0        0        0    1        0          0.0

       Unnamed: 45  Unnamed: 46  Unnamed: 47
0              0.0          NaN          NaN
1              NaN          NaN          NaN
2              NaN          NaN          NaN
3              NaN          NaN          NaN
4              NaN          NaN          NaN
...            ...          ...          ...
14756          NaN          NaN          NaN
14757          0.0          0.0          NaN
14758          NaN          NaN          NaN
14759          NaN          NaN          NaN
14760          NaN          NaN          NaN

[14761 rows x 48 columns]

In [ ]:
Q10

In [ ]:
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')

# Subset the DataFrame for movies with duration between 30 minutes and 180 minutes
subset_df = df[(df['duration'] >= 1800) & (df['duration'] <= 10800)]

# Reset the index for better readability (optional)
subset_df.reset_index(drop=True, inplace=True)

# Display the subset DataFrame
print(subset_df)